export const themes = [
  { value: 'light', label: 'Light', img: '/assets/icons/sun.svg' },
  { value: 'dark', label: 'Dark', img: '/assets/icons/moon.svg' },
  { value: 'system', label: 'System', img: '/assets/icons/computer.svg' },
];

export const sidebarLinks = [
  { value: 'Popular', route: '/popular', img: '/assets/icons/fire.svg' },
  {
    value: 'Exchanges',
    route: '/exchanges',
    img: '/assets/icons/exchanges.svg',
  },
];

export const currencies = [
  { name: 'usd', symbol: '$' },
  { name: 'eur', symbol: '€' },
  { name: 'gbp', symbol: '£' },
  { name: 'jpy', symbol: '¥' },
  { name: 'brl', symbol: 'R$' },
  { name: 'pen', symbol: 'S/.' },
  { name: 'chf', symbol: 'CHF' },
  { name: 'kes', symbol: 'KSh' },
  { name: 'ngn', symbol: '₦' },
  { name: 'qar', symbol: 'ر.ق' },
  { name: 'cny', symbol: '¥' },
  { name: 'php', symbol: '₱' },
  { name: 'uah', symbol: '₴' },
  { name: 'rub', symbol: '₽' },
  { name: 'twd', symbol: 'NT$' },
  { name: 'bgn', symbol: 'лв' },
  { name: 'sar', symbol: 'ر.س' },
  { name: 'kwd', symbol: 'ك.د' },
  { name: 'cop', symbol: 'COL$' },
  { name: 'ugx', symbol: 'USh' },
  { name: 'zar', symbol: 'R' },
  { name: 'dkk', symbol: 'KR' },
  { name: 'nzd', symbol: 'NZ$' },
  { name: 'kzt', symbol: '₸' },
  { name: 'mad', symbol: 'م.د.' },
  { name: 'thb', symbol: '฿' },
  { name: 'pkr', symbol: '₨' },
  { name: 'bob', symbol: '$b' },
  { name: 'bhd', symbol: '.د.ب' },
  { name: 'try', symbol: '₺' },
  { name: 'ars', symbol: 'ARS$' },
  { name: 'bdt', symbol: '৳' },
  { name: 'mxn', symbol: 'Mex$' },
  { name: 'sek', symbol: 'kr' },
  { name: 'huf', symbol: 'Ft' },
  { name: 'hrk', symbol: 'kn' },
  { name: 'aed', symbol: 'د.إ' },
  { name: 'cad', symbol: 'C$' },
  { name: 'aud', symbol: 'A$' },
  { name: 'egp', symbol: 'E£' },
  { name: 'mnt', symbol: '₮' },
  { name: 'ron', symbol: 'lei' },
  { name: 'idr', symbol: 'Rp' },
  { name: 'pln', symbol: 'zł' },
  { name: 'hkd', symbol: 'HKD' },
  { name: 'vnd', symbol: '₫' },
  { name: 'czk', symbol: 'Kč' },
  { name: 'omr', symbol: 'ر.ع.' },
  { name: 'ves', symbol: 'Bs' },
];

export const graphRanges = [
  { days: 1, symbol: '1D' },
  { days: 7, symbol: '7D' },
  { days: 30, symbol: '1M' },
  { days: 90, symbol: '3M' },
  { days: 365, symbol: '1Y' },
];
