import ThemeProvider from '@/context/ThemeProvider';
import './globals.css';
import { Inter, Poppins } from 'next/font/google';
import Header from '@/components/layout/Header';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-logo',
});

export const metadata = {
  title: 'CryptoTracker | Find your favorite coin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${poppins.variable} bg-gray-50 dark:bg-gray-900`}
      >
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
