import ThemeProvider from "@/providers/ThemeProvider";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["500"],
  subsets: ["latin"],
  variable: "--font-logo",
});

export const metadata = {
  title: "CryptoTracker | Find your favorite coin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${poppins.variable} bg-gray-50 dark:bg-gray-900 dark:text-white scrollbar-thin scrollbar-thumb-rounded-xl scrollbar-track-rounded-xl scrollbar-track-gray-200 scrollbar-thumb-gray-300 dark:scrollbar-track-gray-500 dark:scrollbar-thumb-gray-600`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
